# Generated by Django 3.2.25 on 2026-04-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_image_2',
            field=models.CharField(blank=True, default='listings/default-listing-img.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_image_3',
            field=models.CharField(blank=True, default='listings/default-listing-img.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_image_4',
            field=models.CharField(blank=True, default='listings/default-listing-img.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_image_5',
            field=models.CharField(blank=True, default='listings/default-listing-img.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_image_6',
            field=models.CharField(blank=True, default='listings/default-listing-img.jpg', max_length=255),
        ),
    ]
