# Generated by Django 3.2.25 on 2026-08-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20260607_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='checkout_reserved_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
