# Generated by Django 3.2.25 on 2026-08-29 21:03

import checkout.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_reference',
            field=models.CharField(default=checkout.models.generate_purchase_reference, editable=False, max_length=12, unique=True),
        ),
    ]
