# Generated by Django 3.2.25 on 2026-08-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_purchase_purchase_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='billing_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='purchase',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
