# Generated by Django 3.2.25 on 2026-08-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20260829_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='sale_status',
            field=models.CharField(choices=[('pending_review', 'Pending admin review'), ('approved', 'Sale approved'), ('rejected', 'Sale rejected')], default='pending_review', max_length=20),
        ),
    ]
