# Generated by Django 3.2.25 on 2026-09-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_purchase_sale_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='sale_status',
            field=models.CharField(choices=[('pending_review', 'Pending admin review'), ('approved', 'Sale approved'), ('rejected', 'Sale rejected'), ('cancelled', 'Sale cancelled')], default='pending_review', max_length=20),
        ),
    ]
